
zuul:
  routes:
    store-service:
      path: /stores/**
      serviceId: store-service
      stripPrefix: false

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 9999